# 1차: 예전 8x8 아이콘이 있던 것들 (69개)
from sprites import M, S

FACE = S(
 ".....kkkkkk.....", "...kkyyyyyykk...", "..kyyyyyyyyyyk..", ".kyyyyyyyyyyyyk.", ".kyyyyyyyyyyyyk.",
 "kyyyyyyyyyyyyyyk", "kyyyyyyyyyyyyyyk", "kyyyyyyyyyyyyyyk", "kyyyyyyyyyyyyyyk", "kyyyyyyyyyyyyyyk",
 "kyyyyyyyyyyyyyyk", ".kyyyyyyyyyyyyk.", ".kYyyyyyyyyyyYk.", "..kYyyyyyyyyYk..", "...kkYYYYYYkk...", ".....kkkkkk.....")
def face(**rows):
    """rows: r<n>='16글자' 에서 '_'는 바탕 그대로"""
    out = [list(r) for r in FACE]
    for k, v in rows.items():
        y = int(k[1:]); assert len(v) == 16, (k, v)
        for x, c in enumerate(v):
            if c != '_': out[y][x] = c
    return [''.join(r) for r in out]

A = {}
A['octo'] = S(
 ".....kkk", "....kwww", "...kuuuu", "..krrrrr", ".krRrrrr", ".krRrrrr", ".krrkkrr", ".krrkhrr",
 ".krprrrk", "..krrrrr", ".krrkrrr", "krrk.krr", "krk..krr", ".k...krk", "......k.", "........")
A['muscle'] = S(
 "................",
 ".....kkk........",
 "....kyyyk.......",
 "....kyyyk.......",
 "....kyyk........",
 "....kyyk...kkk..",
 "....kyyk.kkyyyk.",
 "....kyyykyyyyyyk",
 "....kyyyyyyyyyyk",
 "...kyyyyyykyyyyk",
 "...kyyyyyyykyyk.",
 "..kyyyyyyyyyyyk.",
 "..kYyyyyyyyyyk..",
 "...kYYyyyyyYk...",
 "....kkkkkkkk....",
 "................")
A['pencil'] = S(
 "............kk..",
 "...........kppk.",
 "..........kpppk.",
 ".........kNkpk..",
 "........kyNkk...",
 ".......kyyyk....",
 "......kyyyk.....",
 ".....kyyyk......",
 "....kyyyk.......",
 "...kyyyk........",
 "..kYyyk.........",
 "..ktYk..........",
 ".kttk...........",
 ".kmk............",
 ".kk.............",
 "................")
A['bubbles'] = S(
 "................",
 ".........kkkk...",
 "........kiiiik..",
 ".......kihiiijk.",
 ".......kiiiiiJk.",
 ".......kiiiiJJk.",
 "..kkk...kiJJJk..",
 ".kihik...kkkk...",
 ".kiiJk..........",
 "..kkk.....kkk...",
 "........kkiiikk.",
 ".......kihiiiijk",
 ".......kiiiiiiJk",
 ".......kiiiiiJJk",
 "........kkJJJkk.",
 "..........kkk...")
A['book'] = S(
 "................",
 "................",
 ".kkkkkk..kkkkkk.",
 "kwwwwwwkkwwwwwwk",
 "kwkkkkwwkwkkkkwk",
 "kwwwwwwwkwwwwwwk",
 "kwkkkkkwkwkkkkwk",
 "kwwwwwwwkwwwwwwk",
 "kwkkkkwwkwkkkwwk",
 "kwwwwwwwkwwwwwwk",
 "kwkkkkkwkwkkkkwk",
 "kwwwwwwwkwwwwwwk",
 "kNNNNNNkkkNNNNNk",
 "kuuuuuukkuuuuuuk",
 ".kkkkkk..kkkkkk.",
 "................")
A['sparkle'] = S(
 "......k.........",
 ".....kyk........",
 ".....kyk........",
 "....kyZyk.......",
 "..kkyZZZykk.....",
 "kkyyZZZZZyykk...",
 "..kkyZZZykk..k..",
 "....kyZyk...kyk.",
 ".....kyk...kyZyk",
 ".....kyk....kyk.",
 "......k......k..",
 ".........k......",
 "........kyk.....",
 ".......kyZyk....",
 "........kyk.....",
 ".........k......")
A['sleepy'] = face(
 r3="__________kkkk__", r4="___________k____", r5="__________kkkk__",
 r7="__kkkk____kkkk__", r9="______kkkk______", r10="_____kwwwwk_____", r11="______kkkk______")
A['cal'] = S(
 "...k......k.....",
 "..kNk....kNk....",
 "kkkNkkkkkkNkkkk.",
 "krrrrrrrrrrrrrk.",
 "krrrrrrrrrrrrrk.",
 "kkkkkkkkkkkkkkk.",
 "kwwwwwwwwwwwwwk.",
 "kwkkwkkwkkwkkwk.",
 "kwwwwwwwwwwwwwk.",
 "kwkkwkkwrrwkkwk.",
 "kwwwwwwwrrwwwwk.",
 "kwkkwkkwkkwkkwk.",
 "kwwwwwwwwwwwwwk.",
 "kNNNNNNNNNNNNNk.",
 "kkkkkkkkkkkkkkk.",
 "................")
A['run'] = S(
 "..........kkk...",
 ".........kyyyk..",
 ".........kyyyk..",
 "..........kkk...",
 "......kkkkk.....",
 ".....kuuuuuk....",
 "....kuukuuuukk..",
 "...kuk.kuuukyyk.",
 "..kyk..kuuuk.kk.",
 "..kk...kBBBk....",
 "......kBBkBBk...",
 ".....kBBk.kBBk..",
 "....kBBk...kBk..",
 "...krrk....krrk.",
 "...kkk.....kkk..",
 "................")
A['bdcake'] = S(
 "...k...k...k....",
 "...y...y...y....",
 "..kpk.kuk.kyk...",
 "..kpk.kuk.kyk...",
 ".kkkkkkkkkkkkk..",
 "kwwwwwwwwwwwwwk.",
 "kwpwwpwwwpwwpwk.",
 "kpPppPppPppPppk.",
 "kbbbbbbbbbbbbbk.",
 "krrbbbrrrbbbrrk.",
 "kbbbbbbbbbbbbbk.",
 "kwwwwwwwwwwwwwk.",
 "kbbbbbbbbbbbbbk.",
 "kNNNNNNNNNNNNNNk",
 ".kkkkkkkkkkkkkk.",
 "................")
A['clapper'] = S(
 "................",
 ".kk.............",
 "kmmkk...........",
 "kwmmmkk.........",
 ".kmwwmmkk.......",
 "..kkmmwwmkk.....",
 "....kkmmwwmk....",
 "kkkkkkkkkkkkkkk.",
 "kmwwmmwwmmwwmmk.",
 "kkkkkkkkkkkkkkk.",
 "kmmmmmmmmmmmmmk.",
 "kmNNNNmmmmmmmmk.",
 "kmmmmmmmNNNNmmk.",
 "kmNNNmmmmmmmmmk.",
 "kkkkkkkkkkkkkkk.",
 "................")
A['ramen'] = S(
 "............kk..",
 "...........kDk..",
 "..........kDk.kk",
 ".........kDk.kDk",
 "........kDk.kDk.",
 "...kkkkkkkkkDkk.",
 ".kkyyyyyyyykkyyk",
 "kyyyyhyywwyyyyyk",
 "kyypppyyywwwyyyk",
 "kkkkkkkkkkkkkkkk",
 "krrrrrrrrrrrrrrk",
 ".krwrrwrrwrrwrk.",
 "..krrrrrrrrrrk..",
 "...kkSSSSSSkk...",
 ".....kkkkkk.....",
 "................")
A['note'] = S(
 "................",
 ".........kkk....",
 ".........kuukk..",
 ".........kuuuuk.",
 ".........kukuuuk",
 ".........kk.kkuk",
 ".........k....kk",
 ".........k......",
 ".........k......",
 "......kkkk......",
 ".....kuuuuk.....",
 "....kuhuuuk.....",
 "....kuuuuuk.....",
 ".....kuuuk......",
 "......kkk.......",
 "................")
A['sun'] = S(
 ".......k", "..k....k", "...k...k", "....kkkk", "...kyyyy", "..kyyZZy", "..kyZZyy", "kkkyyyyy",
 "..kyyyyy", "..kyyyyy", "...kYyyy", "....kkkk", "...k...k", "..k....k", ".......k", "........")
A['plate'] = S(
 "................",
 ".k.k.k.....kk...",
 ".k.k.k....kNNk..",
 ".k.k.k....kNNk..",
 ".kkkkk....kNNk..",
 "..kNk.....kNNk..",
 "..kNk.....kNk...",
 "..kNk.....kNk...",
 "..kNk.....kNk...",
 "..kNk.....kNk...",
 "..kNk.....kNk...",
 "..kNk.....kNk...",
 "..kNk.....kNk...",
 "...k.......k....",
 "................",
 "................")
A['zzz'] = S(
 "................",
 ".........kkkkkk.",
 ".........kuuuuk.",
 "............ku..",
 "...........ku...",
 "..........kuuuuk",
 "....kkkkk.kkkkkk",
 "....kuuuk.......",
 ".......uk.......",
 "......uk........",
 ".....kuuuk......",
 "kkkk.kkkkk......",
 "kuuk............",
 "..uk............",
 ".kuuk...........",
 ".kkkk...........")
A['smile'] = face(
 r5="____kk____kk____", r6="____kk____kk____", r8="_ppp________ppp_",
 r9="___k________k___", r10="____kk____kk____", r11="______kkkk______")
A['clover'] = S(
 "................",
 "...kkk...kkk....",
 "..kgggk.kgggk...",
 "..kglggkgglgk...",
 "..kggggkggggk...",
 "...kkggkggkk....",
 ".kkkkkkgkkkkkk..",
 "kgggggkGkgggggk.",
 "kglgggGGGgggglk.",
 "kggggkkGkkggggk.",
 ".kkkkggkggkkkk..",
 "...kggggkgggk...",
 "...kglggkgglk...",
 "...kggk.kggk....",
 "....kk...kk.kk..",
 "..........kGk...")
A['trophy'] = S(
 "..kkkkkk", ".kkyyyyy", "kyyyyZyy", "kykyyZyy", "kykyyZyy", ".kkyyyyy", "..kYyyyy", "...kYyyy",
 "....kkYy", "......kY", "......kY", ".....kYy", "....kddd", "....kdyy", "....kDDD", "....kkkk")
A['slot'] = S(
 "...........kk...",
 "...kkkkkkkkkrk..",
 "..krrrrrrrrkkk..",
 "..krkkkkkkkrk...",
 "..krkwkwkwkrk...",
 "..krkrkykuk rk..".replace(' ', 'r')[:16],
 "..krkwkwkwkrk...",
 "..krkkkkkkkrk...",
 "..krrrrrrrrrk...",
 "..krryyyyyrrk...",
 "..krrrrrrrrrk...",
 "..kSSSSSSSSSk...",
 ".kkkkkkkkkkkkk..",
 ".kmmmmmmmmmmmk..",
 ".kkkkkkkkkkkkk..",
 "................")
A['disk'] = S(
 "................",
 ".kkkkkkkkkkkkk..",
 ".kBBkNNNNNkBBBk.",
 ".kBBkNNmmNkBBBk.",
 ".kBBkNNmmNkBBBk.",
 ".kBBkNNNNNkBBBk.",
 ".kBBBkkkkkBBBBk.",
 ".kBBBBBBBBBBBBk.",
 ".kBkkkkkkkkkkBk.",
 ".kBkwwwwwwwwkBk.",
 ".kBkwkkkkkkwkBk.",
 ".kBkwwwwwwwwkBk.",
 ".kBkwkkkkkwwkBk.",
 ".kBkwwwwwwwwkBk.",
 ".kkkkkkkkkkkkkk.",
 "................")
A['maple'] = S(
 ".......k", "......ko", ".k...koo", "kok.kooo", "koookooo", ".koooooo", "kooooooo", "kooooooO",
 ".kooooOO", "..kooooo", ".kooookk", "..kkkk.k", "......kD", "......kD", ".......k", "........")
A['tub'] = S(
 ".k..............",
 "kNk.............",
 "kNk..w..w.......",
 "kNk.w..w..w.....",
 "kNk..w..w.......",
 "kNkkkkkkkkkkkkk.",
 "kNiiiiiiiiiiiiik",
 "kkkkkkkkkkkkkkkk",
 "kwwwwwwwwwwwwwwk",
 ".kwhwwwwwwwwwwk.",
 ".kwwwwwwwwwwwNk.",
 "..kwwwwwwwwwNk..",
 "...kkkkkkkkkk...",
 "...kDk....kDk...",
 "...kk......kk...",
 "................")
A['scale'] = S(
 ".......k", ".......k", "..kkkkkk", "..kYyyyy", "..kkkkkk", "..k....k", ".kyk...k", ".kyk...k",
 "kyyyk..k", "kkkkk..k", "kyyyk..k", ".kkk...k", ".......k", "....kkkk", "...kyyyy", "...kkkkk")
A['scroll'] = S(
 "................",
 "...kkkkkkkkkkk..",
 "..kttktttttttk..",
 "..ktkttttttttk..",
 "...kttkkkkkttk..",
 "....kttttttttk..",
 "....ktkkkkkttk..",
 "....kttttttttk..",
 "....ktkkkkkttk..",
 "....kttttttttk..",
 "....ktkkkkttk...",
 "....kttttttttkk.",
 "....kttttttkttk.",
 ".....kkkkkkttk..",
 "...........kk...",
 "................")
A['umbrella'] = S(
 "u......k........",
 "......kkk....u..",
 "....kkrrrkk.....",
 "..kkrrrwrrrkk...",
 ".krrrrwwwrrrrk..",
 "krrrrwwwwwrrrrk.",
 "krrrrwwwwwrrrrk.",
 "kkkkkkkkkkkkkkk.",
 ".......kD.......",
 "u......kD.....u.",
 ".......kD.......",
 ".......kD.......",
 "...u...kD..u....",
 "....kk.kD.......",
 "....kDkDk.......",
 ".....kkk........")
A['check'] = S(
 "................", "................", "............kk..", "...........kgk..", "..........kggk..",
 ".........kggk...", ".kk.....kggk....", "kggk...kggk.....", "kgggk.kggk......", ".kgggkggk.......",
 "..kgggggk.......", "...kgggk........", "....kgk.........", ".....k..........", "................", "................")
A['checkbox'] = S(
 "................",
 ".kkkkkkkkkkkkkk.",
 "kgggggggggggggGk",
 "kglggggggggkkgGk",
 "kgggggggggkwwkGk",
 "kggggggggkwwkgGk",
 "kgkkgggggkwwkgGk",
 "kkwwkgggkwwkggGk",
 "kgkwwkgkwwkgggGk",
 "kggkwwkwwkggggGk",
 "kgggkwwwkgggggGk",
 "kggggkwkggggggGk",
 "kgggggkgggggggGk",
 "kGGGGGGGGGGGGGGk",
 ".kkkkkkkkkkkkkk.",
 "................")
A['dusk'] = S(
 "kkkkkkkkkkkkkkkk",
 "kvvvvvvvvvvvvvvk",
 "kVVVVVVVVVVVVVVk",
 "kppppppkkkppppok",
 "kpppppkyyykpppok",
 "koooookyyykooook",
 "kkkkoookkkoookkk",
 "kmmkoookkkkoookm",
 "kmykkkkkmmkkkkym",
 "kmmkmmykmmkmmkmm",
 "kmykmmmkmykmykmm",
 "kmmkmymkmmkmmkym",
 "kmykmmmkmykmmkmm",
 "kmmkmmmkmmkmykmm",
 "kkkkkkkkkkkkkkkk",
 "................")
A['ribbon'] = S(
 "................", "................", ".kkk....", "kpppk...", "kpPppkkk", "kpPPpkpp", "kpPPpkpP", "kpPpkkpP",
 "kppkpkpp", ".kkpkkkk", "..kpk...", ".kpPk...", ".kpk....", "kpPk....", "kkk.....", "........")
A['clap'] = S(
 "........k.......",
 "....k...k.......",
 ".....k...k......",
 "...k....kkk.....",
 "......kkyyyk....",
 ".....kyykyyyk...",
 "....kyykyyyyyk..",
 "...kyykyyyyyyyk.",
 "...kykyyyyyyyyk.",
 "..kyyyyyyyyyyk..",
 "..kyyyyyyyyyyk..",
 "..kyyyyyyyyyk...",
 "...kYyyyyyyk....",
 "....kYYYYkk.....",
 ".....kkkk.......",
 "................")
A['xmastree'] = S(
 ".......k", "......ky", ".......k", "......kg", ".....kgg", "....kgrg", "....kggg", "...kgggg",
 "..kggygg", "...kgggg", "..kggggr", ".kgrgggg", "kggggggg", ".kkkkkkk", "......kD", "......kk")
A['lock'] = S(
 "................",
 ".....kkkkkk.....",
 "....kNNNNNNk....",
 "...kNkkkkkkNk...",
 "...kNk....kNk...",
 "...kNk....kNk...",
 ".kkkkkkkkkkkkkk.",
 ".kyyyyyyyyyyyyk.",
 ".kyZyyyykkyyyyk.",
 ".kyZyyykmmkyyyk.",
 ".kyyyyyykkyyyyk.",
 ".kyyyyyykkyyyyk.",
 ".kyyyyyyyyyyyyk.",
 ".kYYYYYYYYYYYYk.",
 ".kkkkkkkkkkkkkk.",
 "................")
A['basket'] = S(
 "................",
 ".....kkkkkk.....",
 "....kDk..kDk....",
 "...kDk....kDk...",
 "...kk......kk...",
 ".kkkkkkkkkkkkkk.",
 ".kbdbdbdbdbdbdk.",
 ".kkkkkkkkkkkkkk.",
 "..kbdbdbdbdbdk..",
 "..kdbdbdbdbdbk..",
 "..kbdbdbdbdbdk..",
 "..kdbdbdbdbdbk..",
 "...kbdbdbdbdk...",
 "...kkkkkkkkkk...",
 "................",
 "................")
A['pray'] = S(
 ".......k", "......ky", "......ky", ".....kyy", ".....kyy", "....kyyy", "....kyyy", "...kyyyy",
 "...kyyyy", "..kyyyyy", "..kyyyyy", ".kYyyyyy", ".kYYyyyy", ".kuuuuuu", ".kkkkkkk", "........")
A['cross'] = S(
 "................", "................", "..kk....", "..kkk...", "...kkk..", "....kkk.", ".....kkk", "......kk",
 "......kk", ".....kkk", "....kkk.", "...kkk..", "..kkk...", "..kk....", "........", "........")
A['gym'] = S(
 "................",
 "..kk.......kk...",
 ".kyyk.....kyyk..",
 "..kyyk...kyyk...",
 "...kyyk.kyyk....",
 "....kpppppk.....",
 "....kpppppk.....",
 "...kpppppppk....",
 "..kyyk.kkkyyk...",
 ".kyyk..kyykyyk..",
 "kyyk...kyyk.kk..",
 ".kk.....kk......",
 "......kkkk......",
 ".....kyyyyk.....",
 ".....kyyyyk.....",
 "......kkkk......")
A['chat'] = S(
 "................",
 "..kkkkkkkkkkkk..",
 ".kwwwwwwwwwwwwk.",
 "kwwwwwwwwwwwwwwk",
 "kwwwwwwwwwwwwwwk",
 "kwwkkwwkkwwkkwwk",
 "kwwkkwwkkwwkkwwk",
 "kwwwwwwwwwwwwwwk",
 "kwwwwwwwwwwwwwwk",
 ".kNwwwwwwwwwwNk.",
 "..kkkkwwkkkkkk..",
 ".....kwk........",
 "....kwk.........",
 "....kk..........",
 "................",
 "................")
A['heart'] = S(
 "................", "..kkkk..", ".krrrrkk", "krhhrrrk", "krhrrrrr", "krrrrrrr", "krrrrrrr", ".krrrrrr",
 "..krrrrr", "...krrrr", "....krrr", ".....krr", "......kr", ".......k", "........", "........")
A['melon'] = S(
 "................", "................", "................", "kkkkkkkk", "krrrrrrr", "krrkrrrr", ".krrrrrk",
 ".krrrrrr", "..krkrrr", "..krrrrr", "...krrrr", "...kwwww", "....kggg", ".....kkk", "........", "........")
A['lens'] = S(
 "................",
 "...kkkkk........",
 "..kiiiiik.......",
 ".kihhiiiik......",
 "kiihiiiiiik.....",
 "kiiiiiiiiik.....",
 "kiiiiiiiiik.....",
 "kiiiiiiiiik.....",
 ".kiiiiiiik......",
 "..kiiiiikkk.....",
 "...kkkkkkDDk....",
 "..........kDDk..",
 "...........kDDk.",
 "............kDDk",
 ".............kk.",
 "................")
A['people'] = S(
 "................",
 ".........kkk....",
 "...kkk..kvvvk...",
 "..kuuuk.kvvvk...",
 "..kuuuk.kvvvk...",
 "..kuuuk..kkk....",
 "...kkk..kkkkk...",
 "..kkkkkkvvvvvk..",
 ".kuuuuukvvvvvvk.",
 "kuuuuuuukvvvvvk.",
 "kuuuuuuukvvvvvk.",
 "kuuuuuuukkkkkkk.",
 "kkkkkkkkk.......",
 "................",
 "................",
 "................")
A['confetti'] = S(
 "..........k.....",
 "...k.....kDk....",
 "..kyk...kDk..k..",
 "...k....kk..kpk.",
 "......kkkkkk.k..",
 ".k..kkyyyyyykk..",
 "kuk.kyykyyyyyk..",
 ".k.kyyyyyyyyyyk.",
 "...kyyyyyyyyyyk.",
 "...kkkkkkkkkkkk.",
 "...k.y.r.u.g.p..",
 "....y.r.u.g.p...",
 "...r.u.g.p.y....",
 "....u.g.p.y.r...",
 "...g.p.y.r.u....",
 "................")
A['nope'] = face(
 r5="___kk______kk___", r6="___kk______kk___", r8="_____kkkkkk_____",
 r10="__kk________kk__", r11="___kkk____kkk___", r12="_____kkkkkk_____", r13="____kk____kk____")
A['snow'] = S(
 ".......k", "....k..k", ".....k.k", "..k...kk", "...k..ki", "....kkki", ".kk..kii", "kiikkiii",
 ".kk..kii", "....kkki", "...k..ki", "..k...kk", ".....k.k", "....k..k", ".......k", "........")
A['dizzy'] = face(
 r4="___k_k____k_k___", r5="____k______k____", r6="___k_k____k_k___",
 r9="______kkkk______", r10="_____k____k_____", r11="______kkkk______")
A['lift'] = S(
 "................",
 "kk............kk",
 "kmk..........kmk",
 "kmkkkkkkkkkkkkmk",
 "kmmmmmmmmmmmmmmk",
 "kmkkkkkkkkkkkkmk",
 "kmk...kyyk...kmk",
 "kk...kyyyyk...kk",
 "......kyyk......",
 ".....kuuuuk.....",
 "....kuuuuuuk....",
 ".....kuuuuk.....",
 ".....kBkkBk.....",
 "....kBk..kBk....",
 "....kkk..kkk....",
 "................")
A['medal'] = S(
 "..kkk...kkk.....",
 "..kuuk.kuuk.....",
 "...kuukuuk......",
 "....kuuuk.......",
 "...kkkkkkk......",
 "..kyyyyyyyk.....",
 ".kyyZZZyyyyk....",
 ".kyZyyyyyyyk....",
 ".kyyyykyyyyk....",
 ".kyyykkyyyyk....",
 ".kyyyykyyyYk....",
 ".kyyykkkyyYk....",
 "..kYyyyyyYk.....",
 "...kkkkkkk......",
 "................",
 "................")
A['coffee'] = S(
 "................",
 ".....w...w......",
 "....w...w.......",
 ".....w...w......",
 "................",
 "..kkkkkkkkkkk...",
 "..kwwwwwwwwwkkk.",
 "..kDDDDDDDDDkwk.",
 "..kwhwwwwwwwkwk.",
 "..kwhwwwwwwwkwk.",
 "..kwwwwwwwwwkk..",
 "...kwwwwwwwk....",
 "....kNNNNNk.....",
 ".kkkkkkkkkkkkk..",
 "..kNNNNNNNNNk...",
 "...kkkkkkkkk....")
A['phones'] = S(
 "................", "....kkkk", "..kkmmmm", ".kmmkkkk", ".kmk....", "kmk.....", "kmk.....", "kmk.....",
 "kkkk....", "krrk....", "krRrk...", "krRrk...", "krrrk...", "kkkkk...", "........", "........")
A['warn'] = S(
 ".......k", "......ky", "......ky", ".....kyy", ".....kyy", "....kyyk", "....kyyk", "...kyyyk",
 "...kyyyk", "..kyyyyk", "..kyyyyy", ".kyyyyyk", ".kyyyyyk", "kYYYYYYY", "kkkkkkkk", "........")
A['tulip'] = S(
 "................", "...k..k.", "..kpk.kp", "..kpPkpP", "..kpPPpP", "..kpppPP", "..kppppp", "...kpppp",
 "....kkkk", "......kg", "..kk..kg", "..kgk.kg", "...kgkkg", "....kggg", ".....kkg", "........")
A['relax'] = face(
 r1="___kkk____kkk___", r2="__kyyyk__kyyyk__", r3="__kyyyk__kyyyk__",
 r6="___kkk____kkk___", r8="_pp__________pp_", r10="______kkkk______")
A['zipper'] = face(
 r5="____kk____kk____", r6="____kk____kk____",
 r9="___kkkkkkkkkk___", r10="___kNkNkNkNkk___", r11="___kkkkkkkkkk___")
A['outbox'] = S(
 ".......k", "......ku", ".....kuu", "....kuuu", "...kkkuu", ".....kuu", ".....kuu", ".....kuu",
 "kkkkkkkk", "kNNNNkkk", "kNNNNNNN", "kNNNNNNN", "kNNNNNNN", "knnnnnnn", "kkkkkkkk", "........")
A['bolt'] = S(
 "........kkkkk...",
 ".......kyyyyk...",
 "......kyyyyk....",
 ".....kyyyyk.....",
 "....kyyyyk......",
 "...kyyyyykkkk...",
 "..kyyyyyyyyyk...",
 "..kkkkyyyyyk....",
 ".....kyyyyk.....",
 "....kyyyyk......",
 "....kyyyk.......",
 "...kyyyk........",
 "...kyyk.........",
 "..kyyk..........",
 "..kyk...........",
 "..kk............")
A['folder'] = S(
 "................",
 "................",
 ".kkkkk..........",
 "kyyyyykkkkkkkk..",
 "kYYYYYYYYYYYYk..",
 "kYYkkkkkkkkkkkkk",
 "kYkyyyyyyyyyyyyk",
 "kYkyyyyyyyyyyyk.",
 "kkyyyyyyyyyyyyk.",
 "kkyyyyyyyyyyyk..",
 "kyyyyyyyyyyyyk..",
 "kyyyyyyyyyyyk...",
 "kkkkkkkkkkkkk...",
 "................",
 "................",
 "................")
A['shake'] = S(
 "................",
 "................",
 "................",
 ".kkk........kkk.",
 "kuuuk.kkkk.kuuuk",
 "kuuukkyyyykkuuuk",
 "kuuukyykkyykuuuk",
 "kuuuyykyyykyuuuk",
 "kuuukykyyyykuuuk",
 "kuuukykyyyyykuuk",
 "kuuuk.kyyykyyuuk",
 "kuuuk..kyykyykuk",
 ".kkk....kkkkkkk.",
 "................",
 "................",
 "................")
A['pushpin'] = S(
 "................",
 ".........kk.....",
 "........krrk....",
 ".......krRrrk...",
 "......krRrrrrk..",
 ".....kkrrrrrrrk.",
 "....krrkrrrrrk..",
 "...krrrrkrrrk...",
 "...kSrrrrkkk....",
 "....kSSrrrk.....",
 "....kNkSSk......",
 "...kNk.kk.......",
 "..kNk...........",
 ".kNk............",
 ".kk.............",
 "................")
A['dizzystar'] = S(
 "................",
 "..........k.....",
 ".........kyk....",
 "......kkkyyyk...",
 ".....k..kyZyk...",
 "....k..kyyyyyk..",
 "....k...kyyyk...",
 "....k...kykyk...",
 ".....k..kk.kk...",
 "......kk....k...",
 "........kkkk....",
 "..k.............",
 ".kyk............",
 "..k.............",
 "................",
 "................")
A['sweat'] = S(
 "................",
 ".....k..........",
 "....kuk.........",
 "....kuk.........",
 "...kuhuk........",
 "...kuuuk....k...",
 "....kkk....kuk..",
 "...........kuk..",
 "..k.......kuhuk.",
 ".kuk......kuuuk.",
 ".kuk.......kkk..",
 "kuhuk...........",
 "kuuuk...........",
 ".kkk............",
 "................",
 "................")
A['scooter'] = S(
 "................",
 "..........kk....",
 "..........kmkkk.",
 "...........kmk..",
 "...........km...",
 "..kkkkk....kmk..",
 ".kwwwwwk...kmk..",
 "..kkkkk...kmmk..",
 "...kuuukkkkuuk..",
 "..kuuuuuuuuuuuk.",
 ".kuuuuuuuuuuuuk.",
 ".kkkkkkkkkkkkkk.",
 ".kmmk......kmmk.",
 "kmNNmk....kmNNmk",
 ".kmmk......kmmk.",
 "..kk........kk..")
A['store'] = S(
 "................",
 ".kkkkkkkkkkkkkk.",
 ".kwwwwwwwwwwwwk.",
 ".kwgggwrrrwuuuk.",
 ".kkkkkkkkkkkkkk.",
 "kgwgwgwgwgwgwgwk",
 "kkkkkkkkkkkkkkkk",
 ".kwwwwwwwwwwwwk.",
 ".kwkkkkwkkkkkwk.",
 ".kwkiikwkiiikwk.",
 ".kwkiikwkiiikwk.",
 ".kwkiikwkkkkkwk.",
 ".kwkiikwwwwwwwk.",
 ".kwkiikwwwwwwwk.",
 ".kkkkkkkkkkkkkk.",
 "................")
A['cart'] = S(
 "................",
 "kkk.............",
 ".kDk............",
 "..kkkkkkkkkkkkk.",
 "..knwnwnwnwnwnk.",
 "..kkkkkkkkkkkkk.",
 "...knwnwnwnwnk..",
 "...kkkkkkkkkkk..",
 "....knwnwnwnk...",
 "....kkkkkkkkk...",
 "....kn..........",
 "....kkkkkkkkkk..",
 "................",
 ".....kk....kk...",
 "....kmmk..kmmk..",
 ".....kk....kk...")
A['sneaker'] = S(
 "................",
 "................",
 "................",
 "................",
 ".kkkk...........",
 "kuuuukkk........",
 "kuuuuwkwk.......",
 "kuuuuuwkwkk.....",
 "kuuuuuuwkwukk...",
 "kuuuuuuuuuuuukk.",
 "kuuuuuuuuuuuuuuk",
 "kwwwwwwwwwwwwwwk",
 "kNNNNNNNNNNNNNNk",
 ".kkkkkkkkkkkkkk.",
 "................",
 "................")
A['bus'] = S(
 "................",
 "..kkkkkkkkkkkk..",
 ".kyyyyyyyyyyyyk.",
 ".kkkkkkkkkkkkkk.",
 ".kiikiikiikiiik.",
 ".kiikiikiikiiik.",
 ".kkkkkkkkkkkkkk.",
 ".kyyyyyyyyyyyyk.",
 ".kwwyyyyyyyywwk.",
 ".kyyyyyyyyyyyyk.",
 ".kYYYYYYYYYYYYk.",
 ".kkkkkkkkkkkkkk.",
 "..kmmk....kmmk..",
 "..kmmk....kmmk..",
 "...kk......kk...",
 "................")
A['sunset'] = S(
 "kkkkkkkkkkkkkkkk",
 "kooooooooooooook",
 "kooooookkkoooook",
 "kOOOOOkyyykOOOOk",
 "kOOOOkyyyyykOOOk",
 "kppppkyyyyykpppk",
 "kkkkkkkkkkkkkkkk",
 "kDDkDDDkDDkDDDDk",
 "kDykDyDkDykDyDDk",
 "kDDkDDDkDDkDDDyk",
 "kDykDyDkDykDyDDk",
 "kDDkDDDkDDkDDDDk",
 "kuuuuuuuuuuuuuuk",
 "kUuuUuuuUuuuUuuk",
 "kkkkkkkkkkkkkkkk",
 "................")
A['train'] = S(
 "................",
 "....kkkkkkkk....",
 "...kNNNNNNNNk...",
 "..kNkkkkkkkkNk..",
 "..kNkiiiiiikNk..",
 "..kNkihiiiikNk..",
 "..kNkkkkkkkkNk..",
 "..kNNNNNNNNNNk..",
 "..kuuuuuuuuuuk..",
 "..kNyNNNNNNyNk..",
 "..kNNNNNNNNNNk..",
 "...kkkkkkkkkk...",
 "...kmk....kmk...",
 "..kmk......kmk..",
 ".kkkkkkkkkkkkkk.",
 "................")

EMOJI_A = {
 '🐙':'octo','💪':'muscle','✏':'pencil','🫧':'bubbles','📖':'book','✨':'sparkle','😴':'sleepy','📅':'cal',
 '🏃':'run','🎂':'bdcake','🎬':'clapper','🍜':'ramen','🎵':'note','☀':'sun','🍽':'plate','💤':'zzz',
 '😊':'smile','🍀':'clover','🏆':'trophy','🎰':'slot','💾':'disk','🍁':'maple','🛁':'tub','⚖':'scale',
 '📜':'scroll','☔':'umbrella','✔':'check','✅':'checkbox','🌆':'dusk','🎀':'ribbon','👏':'clap','🎄':'xmastree',
 '★':'star','🔒':'lock','🧺':'basket','🙏':'pray','✕':'cross','🤸':'gym','💬':'chat','❤':'heart',
 '🍉':'melon','🔍':'lens','👥':'people','🎊':'confetti','🙅':'nope','❄':'snow','😵':'dizzy','🏋':'lift',
 '🏅':'medal','☕':'coffee','🎧':'phones','⚠':'warn','🌷':'tulip','💆':'relax','🤐':'zipper','📤':'outbox',
 '⚡':'bolt','📂':'folder','🤝':'shake','📌':'pushpin','💫':'dizzystar','💦':'sweat','🛵':'scooter',
 '🏪':'store','🛒':'cart','👟':'sneaker','🚌':'bus','🌇':'sunset','🚆':'train',
}

A['pray'] = S("......kk", ".....kyY", ".....kyY", "....kyyY", "....kyyY", "...kyyyY", "...kyyyY", "..kyyyyY",
 "..kyyyyY", ".kyyyyyY", ".kyyyyyY", "kyyyyyyY", "kkkkkkkk", ".kuuuuuu", ".kkkkkkk", "........")
PALM = [
 "................", ".....k.k.k......", "....kykykyk.....", "....kykykyk.....", "....kykykyk.k...",
 "....kykykykkyk..", "....kyyyyyykyk..", "..k.kyyyyyyyyk..", ".kykkyyyyyyyyk..", ".kyykyyyyyyyyk..",
 "..kyykyyyyyyk...", "...kyyyyyyyyk...", "....kyyyyyyk....", "....kYyyyyYk....", ".....kkkkkk.....", "................"]
A['clap'] = [PALM[0], ".k...k.k.k....k.", "..k.kykykyk..k.."] + PALM[3:]
A['gym'] = [
 "......kkkk......", ".....kyyyyk.....", ".....kyyyyk.....", "..k...kkkk...k..", ".kyk.kppppk.kyk.",
 "..kykppppppkyk..", "...kkppppppkk...", ".....kppppk.....", ".....kuuuuk.....", "....kuukkuuk....",
 "...kuuk..kuuk...", "..kuuk....kuuk..", "..kyk......kyk..", "..kk........kk..", "................", "................"]
A['dizzystar'] = [
 "................", "..........k.....", ".........kyk....", "......kkkyZykkk.", ".......kyyZyyk..",
 "........kyyyk...", ".......kyykyyk..", ".......kk...kk..", "....Y...........", "...Y............",
 "..Y...........Y.", "..Y..........Y..", "...Y........Y...", "....YY....YY....", "......YYYY......", "................"]
A['nope'] = face(r5="____kk____kk____", r6="____kk____kk____", r8="____rr____rr____", r9="_____rr__rr_____",
 r10="______rrrr______", r11="_____rr__rr_____", r12="____rr____rr____")
A['relax'] = face(r4="____kk____kk____", r5="___k__k__k__k___", r8="_pp__________pp_", r10="______kkkk______")
