# 16x16 픽셀 아이콘. M('8글자') = 좌우 대칭으로 16글자 만들기
def M(l): return l + l[::-1]
def S(*rows): return [r if len(r) == 16 else M(r) for r in rows]

PAL_NEW = {'n':'#8c8796','N':'#cdc9d4','m':'#5c5466','v':'#9a6cc8','V':'#cfb0ec','G':'#3f6e2e','l':'#a8d86a',
           'B':'#3e5e9c','h':'#ffffff','O':'#f7b56b','S':'#9c3b33','Z':'#fff0a6','j':'#43a89a','J':'#a6e3d6',
           'q':'#fde2e8','t':'#f3d2a2','i':'#dff0fb','e':'#6b4a8a'}

SP = {}
SP['acorn'] = S(
 "......kkk.......",
 ".......kDk......",
 "...kkkkkDkkkk...",
 "..kDdDdDdDdDDk..",
 ".kDdDdDdDdDdDdk.",
 ".kdDdDdDdDdDdDk.",
 ".kDDDDDDDDDDDDk.",
 "..kkkkkkkkkkkk..",
 "..kbhbbbbbbbYk..",
 "..kbhbbbbbbbYk..",
 "..kbbbbbbbbYYk..",
 "...kbbbbbbbYk...",
 "...kbbbbbbYYk...",
 "....kbbbbYYk....",
 ".....kkbYkk.....",
 ".......kk.......")
SP['ham'] = S(
 "..kkk...", ".kpppk..", ".kpPpkkk", "..kpkbbb", "..kbbbbb", ".kbbbbbb", ".kbbkkbb", ".kbbkhbb",
 "kbbbbbbw", "kbppbbww", "kbppbwww", "kbbbwwwP", ".kbbwwwk", ".kbbwwww", "..kkbwww", "....kkkk")
SP['house'] = S(
 "..........kk....",
 "..........kSk...",
 ".......kk.kSk...",
 "......krrkkSk...",
 ".....krrrrkkk...",
 "....krrrrrrk....",
 "...krrrrrrrrk...",
 "..krrrrrrrrrrk..",
 ".kSSSSSSSSSSSSk.",
 "..kwwwwwwwwwwk..",
 "..kwkkkwkkkwwk..",
 "..kwkikwkDdkwk..",
 "..kwkkkwkDdkwk..",
 "..kwwwwwkDYkwk..",
 "..kwwwwwkDdkwk..",
 "..kkkkkkkkkkkk..")
SP['pack'] = S(
 "......kkkk......",
 ".....kDkkDk.....",
 "....kkDkkDkk....",
 "...krrrrrrrrk...",
 "..krRrrrrrrrrk..",
 "..krRrrrrrrrrk..",
 "..kSSSSSSSSSSk..",
 "..krrrkkkkrrrk..",
 "..krrkyyyykrrk..",
 "..krrkyDDykrrk..",
 "..krrkyyyykrrk..",
 "..krrkkkkkkrrk..",
 "..krrrrrrrrrrk..",
 "..kSrrrrrrrrSk..",
 "...kSSSSSSSSk...",
 "....kk....kk....")
SP['pin'] = S(
 ".....kkkkkk.....",
 "....krrrrrrk....",
 "...krRhrrrrrk...",
 "..krRhhrrrrrrk..",
 "..krRhrrrrrrrk..",
 "..krrrrkkrrrrk..",
 "..krrrkwwkrrrk..",
 "..krrrkwwkrrSk..",
 "...krrrkkrrSk...",
 "....krrrrrSk....",
 ".....krrrSk.....",
 "......krSk......",
 "......kSk.......",
 ".......k........",
 "....nnnnnnn.....",
 "................")
SP['gear'] = S(
 "......kk", "...kk.kN", "..kNNkkN", "..kNNNNN", "...kNNnn", ".kkNNnkk", "kNNNnk..", "kNNNnk..",
 "kNNNnk..", "kNNNnk..", ".kkNNnkk", "...kNnnn", "..kNNNNn", "..kNNkkN", "...kk.kN", "......kk")
SP['cookie'] = S(
 "................",
 ".....kkkkkk.....",
 "...kkObbbbOkk...",
 "..kObbDbbbbbOk..",
 ".kObbbbbbDbbbOk.",
 ".kbbDbbbbbbbbbk.",
 "kObbbbbbbbbDbbOk",
 "kbbbbbDbbbbbbbbk",
 "kbbDbbbbbbbbbbbk",
 "kObbbbbbbDbbbbOk",
 ".kbbbbDbbbbbDbk.",
 ".kObbbbbbbbbbOk.",
 "..kObDbbbbbbOk..",
 "...kkOObbOOkk...",
 ".....kkkkkk.....",
 "................")
SP['flower'] = S(
 "....kk..kk......",
 "...kpPk.kpPk....",
 "..kpPPkkpPPk....",
 "..kpPkyykPPk.kk.",
 "...kkyYYykk.kVvk",
 "..kVVkyykkk.kVvk",
 ".kVvvVkkuuk..kk.",
 ".kVvvkkuUuuk.k..",
 "..kkkGkkuuk.kGk.",
 "....kGGkkk.kGk..",
 ".....kGGk.kGk...",
 "...kkkkGGkGkkk..",
 "..krrrrkGGkrrrk.",
 "..kSrrrrrrrrrSk.",
 "...kSrrrrrrrSk..",
 "....kkkkkkkkk...")
SP['moon'] = S(
 ".....kkkk.......",
 "...kkyyyk.......",
 "..kyyyZk........",
 ".kyyyZk.........",
 ".kyyZk......k...",
 "kyyyZk.....kZk..",
 "kyyyk.......k...",
 "kyyyk...........",
 "kyyyk...........",
 "kyyyZk..........",
 ".kyyyZk.......kk",
 ".kYyyyZkk...kkyk",
 "..kYyyyyZkkkyyk.",
 "...kYYyyyyyyyk..",
 "....kkYYYYYkk...",
 "......kkkkk.....")
SP['star'] = S(
 ".......k", ".......k", "......ky", "......ky", ".....kyy", "kkkkkkyy", "kyyyyyyy", ".kyyyyyy",
 "..kyyyyy", "...kyyyy", "...kyyyy", "..kyyyyY", "..kyyYkk", ".kyYkk..", ".kkk....", "........")
SP['guitar'] = S(
 "............kkk.",
 "...........kNNk.",
 "..........kNkk..",
 ".........kDk....",
 "........kDk.....",
 ".......kDk......",
 "..kkk.kDk.......",
 ".kOOOkDk........",
 ".kOOOkk.........",
 "kOOkkOOk........",
 "kOOkkOOOk.......",
 "kOOOOOOOOk......",
 ".kOkkkOOOOk.....",
 ".kOOOOOOOOk.....",
 "..kkOOOOkk......",
 "....kkkk........")
SP['gift'] = S(
 "...kk....kk.....",
 "..kyyk..kyyk....",
 "..kyYyk.kyYyk...",
 "...kkyykyykk....",
 ".kkkkkkykkkkkkk.",
 ".kppppkykpppppk.",
 ".kPPPPkykPPPPPk.",
 ".kkkkkkykkkkkkk.",
 "..kppkyyykpppk..",
 "..kpphyyykpppk..",
 "..kppkyyykpppk..",
 "..kppkyyykpppk..",
 "..kppkyyykpppk..",
 "..kPPkyyykPPPk..",
 "..kkkkkkkkkkkk..",
 "................")
SP['dice'] = S(
 "....kkkkkkkk....",
 "...kwwwwwwwwk...",
 "..kwwkkwwwwwwk..",
 ".kwwwkkwwwkkwk..",
 ".kkkkkkkkkkkwwk.",
 ".kwwwwwwwwwkkwk.",
 ".kwkkwwwkkwkwwk.",
 ".kwkkwwwkkwkwwk.",
 ".kwwwwkkwwwkkwk.",
 ".kwwwwkkwwwkwwk.",
 ".kwkkwwwkkwkwk..",
 ".kwkkwwwkkwkwk..",
 ".kwwwwwwwwwkk...",
 ".kNNNNNNNNNk....",
 ".kkkkkkkkkkk....",
 "................")
SP['crown'] = S(
 "................", "................", ".kk.....", ".kyk...k", ".kyk..ky", ".kyyk.ky", ".kyyykyy", ".kyyyyyy",
 ".kyyrryy", ".kyyrryy", ".kyyyyyy", ".kYYYYYY", ".kyyyyuy", ".kyyyyyy", ".kkkkkkk", "................")
SP['bowl'] = S(
 "................",
 "......w.w.......",
 ".....w.w.w......",
 "....kkkkkkkk....",
 "..kkwwhwwwwwkk..",
 ".kwwwwwwhwwwwwk.",
 ".kwhwwwwwwwwhwk.",
 "kkkkkkkkkkkkkkkk",
 "kuuuuuuuuuuuuuuk",
 ".kuhuuuuuuuuuuk.",
 ".kuhuuuuuuuuuBk.",
 "..kuuuuuuuuuBk..",
 "...kkBBBBBBkk...",
 "....kNNNNNNk....",
 "....kkkkkkkk....",
 "................")
SP['drop'] = S(
 ".......k", "......ku", "......ku", ".....kuu", ".....kuu", "....kuuu", "...kuhuu", "...kuhuu",
 "..kuhuuu", "..kuuuuu", "..kuuuuu", "..kuuuuu", "...kuuuu", "...kBuuu", "....kkBB", "......kk")
SP['letter'] = S(
 "................",
 "................",
 ".kkkkkkkkkkkkkk.",
 ".kwkwwwwwwwwkwk.",
 ".kwwkwwwwwwkwwk.",
 ".kwwwkwwwwkwwwk.",
 ".kwwwwkkkkwwwwk.",
 ".kwwwkkrrkkwwwk.",
 ".kwwkkrrrrkkwwk.",
 ".kwkwwkrrkwwkwk.",
 ".kkwwwwkkwwwwkk.",
 ".kwwwwwwwwwwwwk.",
 ".kNNNNNNNNNNNNk.",
 ".kkkkkkkkkkkkkk.",
 "................",
 "................")
SP['meat'] = S(
 "................",
 ".....kkkkk......",
 "...kkOoooOkk....",
 "..kOoohoooook...",
 ".kOohooooooook..",
 ".kooooooooDook..",
 ".koooooDooooook.",
 ".kOoooooooooDok.",
 "..kooDoooooook..",
 "..kkOooooooOk...",
 "...kkkOoooOkkk..",
 "......kkkkkwwk..",
 "..........kwwwk.",
 "...........kwwk.",
 "............kk..",
 "................")
SP['tada'] = S(
 "........k.....k.",
 "..k....kyk...kpk",
 ".kuk....k.....k.",
 "..k..kk...k.....",
 "....kpPk.krk..k.",
 "...kpPk...k..kgk",
 "..kyypk........k",
 "..kyyPk..k......",
 ".kyyykk.kuk.....",
 ".kyyyk...k......",
 "kyyyyk..........",
 "kyyyrk..........",
 "kyyrrk..........",
 "kyrrk...........",
 "krrk............",
 "kkk.............")
SP['mj'] = S(
 "..kkkkkkkkkkkk..",
 ".kwwwwwwwwwwwwk.",
 ".kwwwwwrrwwwwwk.",
 ".kwwrrrrrrrrwwk.",
 ".kwwrwwrrwwrwwk.",
 ".kwwrrrrrrrrwwk.",
 ".kwwwwwrrwwwwwk.",
 ".kwwwwwrrwwwwwk.",
 ".kwwwwwrrwwwwwk.",
 ".kwwwwwrrwwwwwk.",
 ".kwwwwwwwwwwwwk.",
 ".kNNNNNNNNNNNNk.",
 ".kjjjjjjjjjjjjk.",
 ".kjjjjjjjjjjjjk.",
 "..kkkkkkkkkkkk..",
 "................")
SP['mic'] = S(
 ".....kkkkk......",
 "....kNnNnNk.....",
 "...kNnNnNnNk....",
 "...knNnNnNnk....",
 "...kNnNnNnNk....",
 "....knNnNnk.....",
 "....kkkkkkk.....",
 ".....kmmmk......",
 ".....kmmmk......",
 ".....kmhmk......",
 ".....kmmmk......",
 ".....kmmmk......",
 "......kmk.......",
 "......kmk.......",
 "......kmk.......",
 ".......k........")
SP['cake'] = S(
 ".......k........",
 "......kyk.......",
 "......kZk.......",
 "......krk.......",
 "......kwk.......",
 "..kkkkkwkkkkkk..",
 ".kwwwwwwwwwwwwk.",
 ".kwprwwwprwwwpk.",
 ".kpppppppppppPk.",
 ".kbbbbbbbbbbbbk.",
 ".kbbbbbbbbbbbbk.",
 ".kwwwwwwwwwwwwk.",
 ".kbbbbbbbbbbbbk.",
 ".kOOOOOOOOOOOOk.",
 "kNNNNNNNNNNNNNNk",
 ".kkkkkkkkkkkkkk.")
SP['map'] = S(
 "................",
 ".kkkkk.kkkkk....",
 ".ktttkkttttkkkk.",
 ".ktttktttgtkttk.",
 ".ktgtktttggktgk.",
 ".kgggkttttkkttk.",
 ".kttgktuuttkttk.",
 ".kttuuuuttkkttk.",
 ".ktttuutttktrtk.",
 ".kttttktttkrrrk.",
 ".kttttkttkkktrk.",
 ".kttttktttkkttk.",
 ".kkkkktkkkkkkkk.",
 "......kk........",
 "................",
 "................")
SP['pad'] = S(
 "................",
 "................",
 "...kkkkkkkkkk...",
 "..kvvvvvvvvvvk..",
 ".kvvVvvvvvvvvvk.",
 ".kvkvvvvvvvrvvk.",
 ".kkkkkvvvvrvrvk.",
 ".kvkvvvvvvvrvvk.",
 ".kvkvvvkkvvvvvk.",
 ".kvvvvkvvkvvvvk.",
 ".kevvkvvvvkvvek.",
 "..keekk..kkeek..",
 "...kkk....kkk...",
 "................",
 "................",
 "................")
SP['hug'] = S(
 "....kkkk", "..kkyyyy", ".kyyyyyy", ".kyyyyyy", "kyyykyyy", "kyykkkyy", "kyyyyyyy", "kyppyyyy",
 "kyppyyyk", "kyyyyyyk", "kokyyyyk", "koookyyk", ".kooookk", "..kookyy", "...kkkyy", "......kk")
SP['ticket'] = S(
 "................",
 "................",
 "................",
 ".kkkkkkkkkkkkkk.",
 ".kyyyyyykyyyyyk.",
 "kkyZyyyyyyyyykk.",
 "kyyZyrryykyyyyk.",
 ".kyyrrrryyyyyk..",
 ".kyyrrrryyyyyk..",
 "kyyyyrryykyyyyk.",
 "kkyyyyyyyyyyykk.",
 ".kYYYYYYkYYYYYk.",
 ".kkkkkkkkkkkkkk.",
 "................",
 "................",
 "................")
SP['castle'] = S(
 "...k.......k....",
 "...kr.....kr....",
 "...kk.....kk....",
 "..kkkk...kkkk...",
 "..kbbk...kbbk...",
 "..kbbkkkkkbbk...",
 "..kbbkbkbkbbk...",
 ".kkbbkkkkkbbkk..",
 ".kbbbbbbbbbbbk..",
 ".kbkkbbbbbkkbk..",
 ".kbkkbbbbbkkbk..",
 ".kbbbbkkkbbbbk..",
 ".kbbbkDDDkbbbk..",
 ".kbbbkDDDkbbbk..",
 ".kdddkDDDkdddk..",
 ".kkkkkkkkkkkkk..")
# 새로 생기는 장식 아이콘
SP['lantern'] = S(
 ".......k", "......kk", ".....kyy", "....kkkk", "..kkrrrr", ".krRrrrr", ".krRrrrS", "kkkkkkkk",
 "krRrrrrr", "krRrrryy", "kkkkkkkk", ".krRrrrr", "..kkSrrr", "....kkkk", ".....kyk", ".....kyk")
SP['tea'] = S(
 "................",
 "......w...w.....",
 ".....w...w......",
 "......w...w.....",
 "................",
 "..kkkkkkkkkkk...",
 "..kgggggggggk...",
 "..kjjjjjjjjjkkk.",
 "..kjhjjjjjjjkjk.",
 "..kjhjjjjjjjkjk.",
 "..kjjjjjjjjjkk..",
 "...kjjjjjjjk....",
 "....kjjjjjk.....",
 ".kkkkkkkkkkkkk..",
 "..kNNNNNNNNNk...",
 "...kkkkkkkkk....")
SP['envelope'] = S(
 "................",
 "...kkkkkkkkkk...",
 "..krrrrrrrrrrk..",
 "..krkkyyyykkrk..",
 "..krrrkyykrrrk..",
 "..krrrrkkrrrrk..",
 "..krrrrrrrrrrk..",
 "..krrrkkkkrrrk..",
 "..krrkyyyykrrk..",
 "..krrkyrrykrrk..",
 "..krrkyyyykrrk..",
 "..krrrkkkkrrrk..",
 "..krrrrrrrrrrk..",
 "..kSrrrrrrrrSk..",
 "...kkkkkkkkkk...",
 "................")
SP['dragon'] = S(
 "................",
 "....k..k........",
 "....kk.kk.......",
 "...kgkkgk.......",
 "..kgggggkk......",
 ".kgkhgggggk.....",
 ".kggggggllk.....",
 "kGgggkkkllk.....",
 "kkk.k..klllk....",
 "......kgllllk...",
 ".....kgglllk.kk.",
 "....kgglllk.kgk.",
 "....kgllllkkggk.",
 ".....kglllllggk.",
 "......kkgggggk..",
 "........kkkkk...")
SP['blossom'] = S(
 "................",
 ".....kkk........",
 "....kpppk.kkk...",
 "....kpqppkpppk..",
 ".kkk.kpppkqppk..",
 "kpppkkkpkkppk...",
 "kpqpppkykpkk....",
 ".kpppkyYykpppk..",
 "..kkkpkykppqpk..",
 "...kpppkkpppk...",
 "...kpqppk.kkk...",
 "....kppk........",
 ".....kk.........",
 "................",
 "................",
 "................")
SP['chess'] = S(
 "......kk", ".....kmm", "....kmmh", "....kmmm", ".....kmm", "......km", ".....kmm", "....kkkk",
 ".....kmm", ".....kmm", ".....kmm", "....kmmm", "...kkkkk", "..kmmmmm", "..knnnnn", "..kkkkkk")
SP['puzzle'] = S(
 "................",
 "......kkk.......",
 ".....klllk......",
 ".kkkkklllkkkkk..",
 ".kgllllllllllk..",
 ".kghllllllllllk.",
 ".kglllllllllkkk.",
 ".kgllllllllk....",
 "kkglllllllllk...",
 "klllllllllllkkk.",
 "kllllllllllllllk",
 "kkgllllllllllkk.",
 ".kgllllllllllk..",
 ".kGGGGGGGGGGGk..",
 ".kkkkkkkkkkkkk..",
 "................")
SP['card'] = S(
 "..kkkkkkkkkkk...",
 "..kwwwwwwwwwk...",
 "..kwrwwwwwwwk...",
 "..kwwwwvvwwwk...",
 "..kwwwvvvvwwk...",
 "..kwwvkvvkvwk...",
 "..kwwvvvvvvwk...",
 "..kwwyvkkvywk...",
 "..kwwvyvvyvwk...",
 "..kwwwvvvvwwk...",
 "..kwwwwvvwwwk...",
 "..kwwwwwwwwwk...",
 "..kwwwwwwwrwk...",
 "..kwwwwwwwwwk...",
 "..kkkkkkkkkkk...",
 "................")
SP['hourglass'] = S(
 "..kkkkkkkkkkkk..",
 "..kDDDDDDDDDDk..",
 "...kiiiiiiiik...",
 "...kiyyyyyyik...",
 "....kiyyyyik....",
 ".....kiyyik.....",
 "......kyyk......",
 "......kiyk......",
 ".....kiiyik.....",
 "....kiiiyiik....",
 "...kiiiyyyiik...",
 "...kiyyyyyyyk...",
 "...kyyyyyyyyk...",
 "..kDDDDDDDDDDk..",
 "..kkkkkkkkkkkk..",
 "................")
SP['blocks'] = S(
 "................",
 "................",
 "..kkkkkkkkkkkk..",
 "..kbbbbbbbbbbk..",
 "..kkkkkkkkkkkk..",
 ".....kbbbbk.....",
 "..kkkkkkkkkkkk..",
 "..kbbbbbbbbbbk..",
 "..kkkkkkkkkkkk..",
 "..kbbk....kbbk..",
 "..kkkkkkkkkkkk..",
 "..kbbbbbbbbbbk..",
 "..kkkkkkkkkkkk..",
 "..kbbbbbbbbbbk..",
 "..kdddddddddDk..",
 "..kkkkkkkkkkkk..")
SP['amp'] = S(
 "................",
 "..kkkkkkkkkkkk..",
 ".kmmmmmmmmmmmmk.",
 ".kmyNyNyNmmmmmk.",
 ".kkkkkkkkkkkkkk.",
 ".kmnmnmnmnmnmmk.",
 ".kmnkkkkkknmmmk.",
 ".kmnkmmmmkknnmk.",
 ".kmnkmkkmmkmmmk.",
 ".kmnkmkkmmkmnmk.",
 ".kmnkmmmmkkmmmk.",
 ".kmnkkkkkknmmmk.",
 ".kmnmnmnmnmnmmk.",
 ".kkkkkkkkkkkkkk.",
 "..kk........kk..",
 "................")
SP['drum'] = S(
 "..kk.......kk...",
 "...kk.....kk....",
 "....kk...kk.....",
 ".....kkkkk......",
 "...kkwwwwwkk....",
 "..kwwwwwwwwwk...",
 "..kNwwwwwwwNk...",
 "..kkNNNNNNNkk...",
 "..krkyrrrykrk...",
 "..krrkrrrkrrk...",
 "..kryrkrkryrk...",
 "..krrrrkrrrrk...",
 "..kSrryrkyrSk...",
 "...kSSSSSSSk....",
 "....kkkkkkk.....",
 "................")
SP['pedal'] = S(
 "................",
 "...kkkkkkkkkk...",
 "..kjjjjjjjjjjk..",
 "..kjkkjjjjkkjk..",
 "..kjkNkjjkNkjk..",
 "..kjjkjjjjkjjk..",
 "..kjjjjrrjjjjk..",
 "..kjjjjjjjjjjk..",
 "..kkkkkkkkkkkk..",
 "..kNNNNNNNNNNk..",
 "..kNkkkkkkkkNk..",
 "..kNkNNNNNNkNk..",
 "..kNkkkkkkkkNk..",
 "..knnnnnnnnnnk..",
 "..kkkkkkkkkkkk..",
 "................")
SP['keys'] = S(
 "................",
 "................",
 "................",
 "kkkkkkkkkkkkkkkk",
 "kmmmmmmmmmmmmmmk",
 "kmrmymgmmmmmmmmk",
 "kkkkkkkkkkkkkkkk",
 "kwkkwkkwkwkkwkkw",
 "kwkkwkkwkwkkwkkw",
 "kwkkwkkwkwkkwkkw",
 "kwwkwwkwwwkwwkwk",
 "kwwkwwkwwwkwwkwk",
 "kNNkNNkNNNkNNkNk",
 "kkkkkkkkkkkkkkkk",
 "................",
 "................")
SP['chick'] = S(
 "................",
 ".....kkkkk......",
 "....kyyyyyk.....",
 "...kyyyyyyyk....",
 "...kyykyyyyk....",
 "..kkkyyyyyyk....",
 "..koOkyyyyyk....",
 "...kkyyyyyyk....",
 "....kwwwwwwwk...",
 "...kwwkwwwwwwk..",
 "..kwwwwkkwwwwk..",
 "..kwwwwwwwwwwk..",
 "..kwwwwwwwwwk...",
 "...kwwwwwwwk....",
 "....kkkkkkk.....",
 "................")
SP['bunny'] = S(
 "...kk...", "..kwwk..", "..kwpk..", "..kwpk..", "..kwpk.k", "..kwwkkw", "..kwwwww", ".kwwwwww",
 ".kwwkkww", ".kwwkhww", ".kpwwwww", ".kwwwwwk", "..kwwwwk", "...kkwww", "....kwww", ".....kkk")
SP['bear'] = S(
 ".kkk....", "kdbdk...", "kbbdkkkk", ".kdddddd", ".kdddddd", "kddkkddd", "kddkhddd", "kdddddbb",
 "kdddddbb", "kdpddbbb", ".kdddddb", "..kkdddd", ".kdkdddd", ".kdddddd", "..kddddd", "...kkkkk")
SP['rainbow'] = S(
 "................",
 "................",
 "....kkkkkkkk....",
 "..kkrrrrrrrrkk..",
 ".krrooooooooorrk",
 "kroyyyyyyyyyyork",
 "kroygggggggggyok",
 "kroyguuuuuuugyok",
 "kroygukkkkkugyok",
 "kroygk.....kgyok",
 "kkkkkk......kkkk",
 "kwwwwk.....kwwwk",
 "kwwwwwk...kwwwwk",
 ".kkkkkk....kkkk.",
 "................",
 "................")
SP['cloud'] = S(
 "................",
 "................",
 "................",
 "......kkkk......",
 ".....kwwwwk.....",
 "...kkwwwwwwkk...",
 "..kwwhwwwwwwwk..",
 ".kkwhwwwwwwwwkk.",
 "kwwwwwwwwwwwwwwk",
 "kwwwwwwwwwwwwwwk",
 "kiwwwwwwwwwwwwik",
 ".kiiiiiiiiiiiik.",
 "..kkkkkkkkkkkk..",
 "................",
 "................",
 "................")
SP['berry'] = S(
 "......k.........",
 "....kkGkk.......",
 "...kgGgGgk......",
 "..kkggkggkk.....",
 ".krrkkkkkrrk....",
 "krrryrrrrrrrk...",
 "krhrrrryrrrrk...",
 "krhrryrrrryrk...",
 "krrrrrrrrrrrk...",
 ".kryrrrryrrk....",
 ".krrrrrrrrrk....",
 "..krrryrrrk.....",
 "...kSrrrSk......",
 "....kSSSk.......",
 ".....kkk........",
 "................")
SP['dango'] = S(
 "............k...",
 "......kkk..kDk..",
 ".....kpppkkDk...",
 "....kppqpkDk....",
 "....kppppkk.....",
 "...kkkpppk......",
 "..kwwwkkk.......",
 ".kwwhwwk........",
 ".kwwwwwkk.......",
 "kkkwwwk.k.......",
 "kgggkk..........",
 "kglggk..........",
 "kgggk...........",
 "kkkk............",
 "kD..............",
 "k...............")
SP['kitten'] = S(
 ".kk.....", ".kok....", ".kook..k", ".koookko", "kooooooo", "kooooooo", "kookkooo", "koohkooo",
 "kooooooo", "kppowwww", ".koowwwk", "..kowwww", "..kkoooo", ".kooooOO", ".kooooOO", "..kkkkkk")
SP['butterfly'] = S(
 "................",
 ".kkk.......kkk..",
 "kvVvk.k.k.kvVvk.",
 "kvVVvkk.kkvVVvk.",
 "kvVVvvkkkvvVVvk.",
 "kvvVvvkmkvvVvvk.",
 ".kvvvvkmkvvvvk..",
 "..kkkvkmkvkkk...",
 "..kVVvkmkvVVk...",
 ".kVyVvkmkvVyVk..",
 ".kVVvk.k.kvVVk..",
 "..kkk.....kkk...",
 "................",
 "................",
 "................",
 "................")
SP['mushroom'] = S(
 "......kkkk......",
 "....kkrrrrkk....",
 "...krrwwrrrrk...",
 "..krrwwwrrrwrk..",
 ".krrrwwrrrwwwrk.",
 ".krwrrrrrrrwwrk.",
 "krwwwrrrrrrrrrrk",
 "kSrwrrrrwwrrrrSk",
 ".kkSSSSSSSSSSkk.",
 "...kwwkwwkwwk...",
 "...kwwkwwkwwk...",
 "...kwwkkkkwwk...",
 "...kwwkDDkwwk...",
 "...kNwkDDkwNk...",
 "...kkkkkkkkkk...",
 "................")
SP['bed'] = S(
 "................",
 "................",
 "kk..............",
 "kDk.............",
 "kDk.kkkk........",
 "kDkkwwwwk.......",
 "kDkwwwwwwkkkkkkk",
 "kDkkkkkkkpppppppk"[:16],
 "kDkpqpqpqpqpqpqk",
 "kDkppppppppppppk",
 "kDkPPPPPPPPPPPPk",
 "kDkkkkkkkkkkkkkk",
 "kDDDDDDDDDDDDDDk",
 "kdkkkkkkkkkkkkdk",
 "kDk..........kDk",
 "kkk..........kkk")
SP['sofa'] = S(
 "................",
 "................",
 "................",
 "...kkkkkkkkkk...",
 "..kjjjjjjjjjjk..",
 "..kjJjjjjJjjjk..",
 "..kjjjjjjjjjjk..",
 ".kkkkkkkkkkkkkk.",
 "kjjkJJJJkJJJJkjk"[:16],
 "kjjkjjjjkjjjjjjk",
 "kjjkkkkkkkkkkjjk",
 "kjjjjjjjjjjjjjjk",
 "kjjjjjjjjjjjjjjk",
 "kkkkkkkkkkkkkkkk",
 ".kDk........kDk.",
 ".kk..........kk.")
SP['books'] = S(
 "................",
 "................",
 "..kkkkkkkkkkk...",
 "..kuuuuuuuuuuk..",
 "..kwwwwwwwwwkk..",
 "...kkkkkkkkkkkk.",
 "...krrrrrrrrrrk.",
 "...krwyyyyrrrSk.",
 "..kkkkkkkkkkkkk.",
 "..kggggggggggk..",
 "..kgwyyyggggGk..",
 ".kkkkkkkkkkkkkk.",
 ".kvvvvvvvvvvvvk.",
 ".kvwyyyyvvvvvek.",
 ".kkkkkkkkkkkkkk.",
 "................")
SP['frame'] = S(
 "................",
 ".kkkkkkkkkkkkkk.",
 ".kyYyYyYyYyYyYk.",
 ".kYkkkkkkkkkkyk.",
 ".kykiiiiiiiikYk.",
 ".kYkiiiiyyiikyk.",
 ".kykiiiiyyiikYk.",
 ".kYkiiiiiiiikyk.",
 ".kykiigiiiiikYk.",
 ".kYkiggggiiikyk.",
 ".kykgggggggkkYk.",
 ".kYkkkkkkkkkkyk.",
 ".kyYyYyYyYyYyYk.",
 ".kkkkkkkkkkkkkk.",
 "................",
 "................")
SP['candle'] = S(
 ".......k........",
 "......kok.......",
 ".....koyok......",
 ".....kyZyk......",
 ".....koyok......",
 "......kmk.......",
 ".....kkkkk......",
 ".....kwwwk......",
 ".....kwhwk......",
 ".....kwwwk......",
 ".....kwwwk......",
 ".....kwwNk......",
 "...kkkkkkkkk....",
 "..kyyyyyyyyyk...",
 "...kkkkkkkkk....",
 "................")
SP['whisky'] = S(
 "................",
 "................",
 "..k..........k..",
 "..kiiiiiiiiiik..",
 "..kiiiiiiiiiik..",
 "..kihiiiiiiiik..",
 "..kihOOOOOOOik..",
 "..kiOOiiiOOOik..",
 "..kiOOiJJiOOik..",
 "..kiOOiiiOOOik..",
 "..kiOOOOOOOOik..",
 "..kiiiiiiiiiik..",
 "..kNNNNNNNNNNk..",
 "..kkkkkkkkkkkk..",
 "................",
 "................")
SP['tv'] = S(
 "....k.....k.....",
 ".....k...k......",
 "......k.k.......",
 ".kkkkkkkkkkkkkk.",
 ".kDDDDDDDDDDDDk.",
 ".kDkkkkkkkkkDDk.",
 ".kDkuuuuuuukDNk.",
 ".kDkuhuuuuukDDk.",
 ".kDkuuuuuuukDNk.",
 ".kDkuuuuuuukDDk.",
 ".kDkkkkkkkkkDDk.",
 ".kDDDDDDDDDDDDk.",
 ".kkkkkkkkkkkkkk.",
 "..kk........kk..",
 "................",
 "................")
SP['fountain'] = S(
 ".......kk.......",
 "......kuuk......",
 ".....kuhuuk.....",
 "....k.kuuk.k....",
 "...ku..kk..uk...",
 "..ku...kk...uk..",
 "..k....kk....k..",
 "..u...kNNk...u..",
 ".kkkkkkkkkkkkkk.",
 "kNuuuuuuuuuuuuNk",
 "kNuhuuuuuuuuuuNk",
 ".kNNNNNNNNNNNNk.",
 "...kNNNNNNNNk...",
 "...knNnNnNnNk...",
 "..kkkkkkkkkkkk..",
 "................")

EMOJI = {  # 이모지 → 아이콘 이름 (이번에 고치는 것)
 '🌰':'acorn','🐹':'ham','🏠':'house','🎒':'pack','📍':'pin','⚙':'gear',
 '🍪':'cookie','💐':'flower','🌙':'moon','⭐':'star','🎸':'guitar','🎁':'gift','🎲':'dice','👑':'crown',
 '🍚':'bowl','💧':'fountain','💌':'letter','🍗':'meat','🎉':'tada','🀄':'mj','🎤':'mic','🍰':'cake',
 '🗺':'map','🎮':'pad','🤗':'hug','🎟':'ticket','🏰':'castle','🏮':'lantern','🍵':'tea','🧧':'envelope',
 '🐉':'dragon','🌸':'blossom','♟':'chess','🧩':'puzzle','🃏':'card','⏳':'hourglass','🧱':'blocks',
 '🔊':'amp','🥁':'drum','🎛':'pedal','🎹':'keys','🐣':'chick','🐰':'bunny','🧸':'bear','🌈':'rainbow',
 '☁':'cloud','🍓':'berry','🍡':'dango','🐱':'kitten','🦋':'butterfly','🍄':'mushroom','🛏':'bed',
 '🛋':'sofa','📚':'books','🖼':'frame','🕯':'candle','🥃':'whisky','📺':'tv',
}

if __name__ == '__main__':
    bad = [(k, i, len(r)) for k, v in SP.items() for i, r in enumerate(v) if len(r) != 16]
    bad += [(k, 'rows', len(v)) for k, v in SP.items() if len(v) != 16]
    print('sprites', len(SP), 'bad', bad)
    print('missing', [e for e, n in EMOJI.items() if n not in SP])

SP['dice'] = S(
 "................",
 "..kkkkkkkkkkkk..",
 ".kwwwwwwwwwwwwk.",
 ".kwhwwwwwwwwwwk.",
 ".kwkkwwwwwwkkwk.",
 ".kwkkwwwwwwkkwk.",
 ".kwwwwwwwwwwwwk.",
 ".kwwwwwrrwwwwwk.",
 ".kwwwwwrrwwwwwk.",
 ".kwwwwwwwwwwwwk.",
 ".kwkkwwwwwwkkwk.",
 ".kwkkwwwwwwkkwk.",
 ".kwwwwwwwwwwwwk.",
 ".kNNNNNNNNNNNNk.",
 "..kkkkkkkkkkkk..",
 "................")
SP['kitten'] = S(
 ".kk.....", ".kpk....", ".kppk..k", ".kbbbkkb", "kbbbbbdb", "kbbbbbbd", "kbbkkbbb", "kbbhkbbb",
 "kbbbbbbb", "kppbwwww", ".kbbwwwk", "..kbwwww", "..kkbbbb", ".kbbbbww", ".kbbbbww", "..kkkkkk")
